server:
  port: 9004

spring:
  application:
    name: index12306-pay${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: localhost:8686
        port: 8719
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: 123456

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: index12306_pay-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

pay:
  alipay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnA3XLhEMsf6sVmCETxsj1mOg0lv/8cUe3UgY3TzTzbjLx41b4li8BqIRlRhyvEU6qfZsTxa5nLrZVrjn/SvpU0TmIu1U2f1T31dejN3j/pellFCicIEdVhH2Dod2Sc47gSAjaFqm7taNkAxfiEqRT/LDfmonZQSW9d3l2lbA+7RznOCsFgvCNnwY0hddGhNsjGT3O4YR9Nxtf/mYGbJbT/FpapUcgMRRkaNwyOt8Btz51j/1rXwEEHs8vnuTQn6H61ENGX8heTD9sOp3j+6jZ1CK2RcftSjgFE8N9ECVXBIpIBkeqm1TRLX8iDRukJdwQoKjeUFXckTAPFNzEPwwmQIDAQAB
    app-id: 9021000140627129
    charset: UTF8
    format: json
    notify-url: http://strumcode.free.idcfengye.com/api/pay-service/callback/alipay
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYRRy9R7X2dbK9uddWXSuKfM8yScnmYg47JO2qQXieXZUAV539pHXlo8GoLPa3q7C2j6tpOMwGJgkisfuf6Rr5JHnGbP6onCCB11/OOm1+teBWc2kJoDASQ4pzR4fh7fNiWmafjdGcRaf3qo4KIUGNEPH6Yc9rQULUcbRnfGyW+h91WYCgWtulSfpqSRtx7/yJc1Ilr2vGfKJGDXrbykXhvxYtJPPVKZ/ua9ncmi9E5fA3ODw59G2mpac60jaHKynzKqT+RkLjeswccJv/+jA2QxejZV/Bbce0OHXtwqTiNr3yY8ghdLf9W5OQTIA08FFVloWVN6OLidbqug1KkToDAgMBAAECggEAJNVK/2pSVNzhsM08jrKY7rYENMjuouEDSkFDkFSoBb7jZSLMn+dhcXwsQy8lOwa4B2E3eIt5pt8ahJ8DHAp6MNwm7N2+uDCUGHRtw2gUxnreWmsudFqgZjqaSgp6jydNIXR2sI/QrXmYCOvj0gV7YtE/h26TiwFNVjBvED1j0x0sGqj9FtLmflsTd2e1pdBHHgCC9EvtzsM18JMWPZy3jvzfBKCt7gVd638nwPwZP760uxOYQobwBfzbsSUhk9SBV7rUNfmDFgrNrSDmo4e6SThVMmaKj2DZUKIgeB0bwWy/9AeUZz9I3LLVglBf8HlNHe5JhLBgQiwkqg2iTcWkoQKBgQDWOPOiB4+/EP3lYj9YYLAJlPZ9IKXU+X3L01lPsHIJLMkHv+/98r4t49K6xRJ7pKdqpqcDqkxvLV1CtqzTYNCzF5I785s5uCWZRkFA3JeecATwVIBJXjqqSgOHY3vkzZPBEAKAKuqZrR0kXmMkXSkXSGyGJQtb9zXsGYRkydgb0wKBgQC19y8+YDWviplWuzev5A0+in7qe+Qr75W/uxSPqlosFC5dmA2pmrt6S6BaFGIva/0lPkUbt9zKUNVCjl7tq81XSLDgRKlOlQaPg2IMqpbgf52yWZK7P1f8j7I1imVvL1JefRKdjVqoF3BYeMnhqrRKlWa5e923+rOyIh/NwCN7EQKBgQDBOWN/7cQZuhDZGzI53BRMwEFIge8yV8vA0qTHPUbOwceeJuEotRAXQlxsPJ+8SLr9ds5EfxIsYcWyDCV9D+GO+J7dVpDXkiLPys/G2nIj5bR+til0g/r0aIggUXqJ2WgBhxhKVOuAq+YSTNSuEx2iM6A3qyhAzo2jpSyG4Iz+IwKBgQCx+nyuEOJRuUmz6FhWZMODiWkLpnQNeUBKEQzSXDfoZzDWgJPUcTCwNGo50Tgb1A79L4Pe0Z5WEGwWtjQpWWH13naKVP4Yi3CoTERJyUzbdlbjC/OVzCYeNNqEvcHq1ylEnCbqDUk/ofVTw4kKfbHsRWb9Qycg/UhnkjLzRtwtUQKBgGUNWuj4rv4IeR+wgv6i1vPKlC6Iedn2K0PFcpKWn/JDvNpcxCMxWS0OBMFqwiBuIYlnsTxE/s8Kdau8ixo2Ts1KcKx8j5H/Ql7PviDAXWL2Ddc8NAMcrCXszMEvcGPnt8Nv8nz1Ih0BuWOvoHNML8a2uSD69+idjr4TyFSg5trb
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    sign-type: RSA2

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
